name: Build Frontend

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      module:
        required: true
        type: string
      profiles_active:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BUILD_ENV=${{ inputs.profiles_active }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project }}-${{ inputs.module }}:latest \
            .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project }}-${{ inputs.module }}:latest
